#!/usr/bin/ruby

require 'fileutils'
require 'open3'
require 'tempfile'
require 'date'
require 'method_source'
require 'mysql2'
require 'net/http'

require './sources/logger.rb'
require './sources/basic/validation'
require './sources/config/generic_config.rb'
require './sources/config/general_config.rb'
require './sources/distributed/agent.rb'
require './sources/options.rb'
require './sources/database/database.rb'
require './sources/collector.rb'
require './sources/distributed/transfer.rb'
require './sources/approach/target.rb'
require './sources/launch.rb'
require './sources/misc/ssh_sharing.rb'

if false
  require './profiling/profiler.rb'
  class Object
    prepend MethodLogger
  end
end

series = Time.now.to_i.to_s
logger = CustomLogger.new(series)
options = Options.new(logger, ARGV)
database = Database.new(logger)
config = GeneralConfig.new(options.workload, database.project_codes)
hook = config.get(:series_benchmark)
hosts = options.hosts
options.check_hook(hook) # check if hooks directory exists and contains mandatory files
agent = Agent.new(nil, nil)

logger.info("Checking SSH persistance on the central node") # maximize SSH performance
ssh_sharing_enable

hosts.each do |host|
  logger.info("Checking SSH availability of benchmark node '#{host}'")
  logger.error("#{agent.error}") if !agent.available?(host)
end

hosts.each do |host|
  logger.info("Checking if another BBH instance is running on benchmark node '#{host}'")
  logger.error("another instance of BBH is running on '#{host}'") if agent.run(host, :bbh_running?) == "true"
end

hosts.each do |host|
  logger.info("Checking CLI dependencies on benchmark node '#{host}'")
  [ "ruby", "curl", "mpstat", "iostat" ].each { |tool| logger.error("'#{tool}' is missing ") if !agent.run(host, :file_exists?, "#{tool}") }
end

# TODO: this check is benchmark-specific, such checks should perform automatically, as part of config checks
# check if config path exists on the nodes
if config.get(:startup_actor) == "self"
  logger.info("Checking actor: 'self' specificed, actor in the hook will be used")
else
  hosts.each do |host|
    logger.info("Checking actor on the benchmark nodes")
    logger.error("actor '#{config.get(:startup_actor)}' is missing on '#{host}'") if !agent.run(host, :file_exists?, config.get(:startup_actor))
  end
end

target = Target.new(agent, logger, config.get(:startup_target))

logger.info("Checking target '#{target.protocol}://#{target.path}'")
hosts.each { |host| target.check(host) }

unless options.mode == :space
  hosts.each do |host|
    logger.info("Checking if CPU is idle on '#{host}'")
      logger.error("CPU utilization >= 10%, no good for benchmarking") if agent.run(host, :cpu_idle) < 90
    logger.info("Checking if storage is idle on '#{host}'")
      logger.error("IO utilization >= 10%, no good for benchmarking") if agent.run(host,:io_idle) < 90
  end
end

config.delayed_init

# first phase of description substituion - here we substitute all the variables from the config file
config.description_substitute

config.set(:startup_target, target.path)

# collector is a permanent agent assigned to each node to store its infrastructure information and perform actions on it
collector = Hash.new
mode = hosts.size > 1 ? "multiple" : "single"
hosts.each do |host|
  logger.info("Initializing workload '#{hook}' on '#{host}'")
  collector[host] = Collector.new(config, host, mode, logger, series, target)
end

# create database table for the requested benchmark, if it doesn't exist yet
database.table_set(hook)

if target.io_schedulers_apply?

  database.table_add_io_schedulers if target.io_schedulers_apply?

  # enable all available kernel IO schedulers on the nodes
  logger.info("Checking available kernel IO schedulers")
  hosts.each do |host|
    %w[mq-deadline kyber bfq none].each do |scheduler|
      `ssh -o StrictHostKeyChecking=no #{host} sudo modprobe -q #{scheduler}`
    end
  end

  logger.info("Checking specification of kernel IO schedulers")
    config.get(:iterate_schedulers).each do |scheduler|
      system_schedulers = `cat /sys/block/sda/queue/scheduler`.strip + " N/A"
      logger.error("unknown IO scheduler '#{scheduler}'") unless system_schedulers.include?(scheduler)
  end
end

# Calculate size of the parameter space, and add it to the config for reporting purposes
parameter_space_size = config.parameter_space_size
config.merge({ parameter_space_size: parameter_space_size })
if options.mode == :space
  config.parameter_space_dimensions { |line| logger.info("dimension #{line}") }
  logger.info("parameter space size is #{parameter_space_size} invocations")
  exit 0
end

#unless Object.method_defined?(:invocation)
logger.info("loading integration hook")
load "./sources/hooks/#{hook}/invocation.rb"
#end

config.merge( { startup_target_protocol: target.protocol } )

# check if Telegram chat is configured and active
def check_telegram_logging(logger)
  token_file = File.expand_path("~/.bbh/telegram")
  return { token: nil, chat_id: nil } if not File.exist?(token_file)
  
  token = File.read(token_file).chomp
  uri = URI("https://api.telegram.org/bot#{token}/getUpdates")
  response = Net::HTTP.get(uri)
  updates = JSON.parse(response)
    logger.error "telegram bot has gone inactive, please send something to it and re-run the benchmark" if updates["result"] == []
    updates["result"].each do |update|
      return { token: token, chat_id: update['message']['chat']['id'] }
    end
    raise "Chat ID not found for #{name} #{surname}"
end

# set Telegram chat for the benchmarks nodes to report to, nil means there's no chat configured
token = check_telegram_logging(logger)[:token]
chat_id = check_telegram_logging(logger)[:chat_id]
config.merge( { token: token} )
config.merge( { chat_id: chat_id } )

#TODO: here, we've returned to the current restrictions of the agent functionality: class must respond to value method, and only a single function can transfer.

hosts.each do |host|
  config.merge(collector[host].infra_static)
  logger.info("Launching workload '#{hook}' on '#{host}'")
  collector[host].detach(host, :launch, config, dependencies: [:invocation, :dimensions, :dimension_naming, :prepare])
end

logger.info("Workload '#{hook}' series #{series} has launched on '#{hosts.join(', ')}'")

