#!/usr/bin/bash

### Depending on the Linux distro installed, install dependencies

source /etc/os-release

if [[ "$ID" == "ol" ]] || [[ "$ID" == "rhel" ]] || [[ "$ID" == "centos" ]]; then
        sudo yum -y install git ruby ruby-devel mysql sysstat rubygem-mysql2 rubygem
        gem install --user-install method_source ruby-mysql2 ruby-mysql net-ssh sourcify
elif [[ "$ID" == "ubuntu" ]]; then
        sudo apt -y install ruby ruby-dev ruby-mysql2 libmysqlclient-dev mysql-client sysstat
        gem install --user-install method_source mysql2 net-ssh sourcify
        export GEM_PATH="$(ruby -e 'puts Gem.user_dir'):$GEM_PATH"
fi

### Set up MySQL database for BBH

mysql_account="benchmarker"
mysql_password="sklfnslefwerqe"
mysql_url="127.0.0.1"

# Check if MySQL installed
echo -n "Checking if MySQL installed..."
if [ ! -f "$(which mysqld)" ]; then
	echo "Please install MySQL server"
	exit 1
elif [ ! -f "$(which mysql)" ]; then
	echo "Please install MySQL client"
	exit 1
fi

echo "Checking if MySQL runs..."
sudo systemctl start mysqld

echo "Don't forget to allow MySQL in your firewall and/or network security rules"

# Set MySQL access credentials
echo "Creating client access credentials for MySQL..."
echo "[client] \
user = $(mysql_account) \
password = $(mysql_password) \
host = $(mysql_url)" > ~/.my.cnf
exit 0
# Configure MySQL
echo "Creating MySQL user..."
mysql -N -B -e "create user '$mysql_account'@'%' identified by '$mysql_password';"

echo "Creating MySQL database..."
mysql -N -B -e "create database benchmarking;"

echo "Creating table of projects..."
mysql benchmarking -N -B <<EOF
create table projects (
    code varchar(20) not null,
    description varchar(200) not null,
    owner_name varchar(50) not null,
    owner_email varchar(50) not null
);
EOF


comment_out() {
echo "Creating table 'fio'..."
mysql benchmarking -N -B <<EOF
create table fio (
    seriesid int not null,
    usecase varchar(500),
    host varchar(50) not null,
    shape varchar(50) not null,
    filesystem varchar(50) not null,
    storage varchar(50) not null,
    drives int not null,
    operation varchar(50) not null,
    threads int not null,
    iodepth int,
    scheduler varchar(50),
    iops int,
    bandwidthmbs int,
    avglatencyusec double,
    inqueue bigint,
    utilization double,
    iteration int not null,
    architecture varchar(10) not null,
    osrelease varchar(50) not null,
    oskernel varchar(50) not null,
    os_cpu varchar(50) not null,
    cores int not null,
    ram int not null,
    location varchar(50),
    image varchar(500),
    benchmark varchar(50) not null,
    command varchar(500) not null,
    device varchar(50) not null,
    error varchar(500),
    config_operations varchar(500) not null,
    config_iodepth varchar(50) not null,
    config_jobs_from int not null,
    config_jobs_to int not null,
    config_increment int not null,
    config_schedulers varchar(500) not null,
    config_hosts varchar(500),
    project_description varchar(500),
    owner_name varchar(50),
    owner_email varchar(50),
    project_code varchar(50),
    project_tier varchar(50)
);
EOF
}

echo "Done"

echo "Don't forget to set MySQL access in ~/.my.cnf"

